module homer.tastyworld.frontend.starterpack {
    requires javafx.controls;
    requires org.jetbrains.annotations;
    requires org.apache.httpcomponents.core5.httpcore5;
    requires org.apache.httpcomponents.client5.httpclient5;
    requires com.fasterxml.jackson.databind;
    requires com.fasterxml.jackson.datatype.jsr310;
    requires org.slf4j;
    requires com.rabbitmq.client;
    requires java.sql;
    requires java.desktop;
    requires com.fazecast.jSerialComm;
    requires static lombok;

    opens homer.tastyworld.frontend.starterpack.api.evotor.mobcashier to com.fasterxml.jackson.databind;
    opens homer.tastyworld.frontend.starterpack.api.evotor.mobcashier.authorize to com.fasterxml.jackson.databind;
    opens homer.tastyworld.frontend.starterpack.api.sra to com.fasterxml.jackson.databind;
    opens homer.tastyworld.frontend.starterpack.api.sra.entity.current to com.fasterxml.jackson.databind;
    opens homer.tastyworld.frontend.starterpack.api.sra.entity.menu to com.fasterxml.jackson.databind;
    opens homer.tastyworld.frontend.starterpack.api.sra.entity.misc to com.fasterxml.jackson.databind;
    opens homer.tastyworld.frontend.starterpack.api.sra.entity.order to com.fasterxml.jackson.databind;
    opens homer.tastyworld.frontend.starterpack.api.sra.entity.order.names to com.fasterxml.jackson.databind;

    exports homer.tastyworld.frontend.starterpack;
    exports homer.tastyworld.frontend.starterpack.api.notifications;
    exports homer.tastyworld.frontend.starterpack.api.sra;
    exports homer.tastyworld.frontend.starterpack.api.sra.entity.current;
    exports homer.tastyworld.frontend.starterpack.api.sra.entity.menu;
    exports homer.tastyworld.frontend.starterpack.api.sra.entity.misc;
    exports homer.tastyworld.frontend.starterpack.api.sra.entity.order;
    exports homer.tastyworld.frontend.starterpack.api.sra.entity.order.names;
    exports homer.tastyworld.frontend.starterpack.base;
    exports homer.tastyworld.frontend.starterpack.base.config;
    exports homer.tastyworld.frontend.starterpack.base.exceptions.api.engine;
    exports homer.tastyworld.frontend.starterpack.base.exceptions.api.notifications;
    exports homer.tastyworld.frontend.starterpack.base.exceptions.api.sra;
    exports homer.tastyworld.frontend.starterpack.base.exceptions.controlled;
    exports homer.tastyworld.frontend.starterpack.base.exceptions.unexpected;
    exports homer.tastyworld.frontend.starterpack.utils.managers.cache;
    exports homer.tastyworld.frontend.starterpack.utils.managers.external.payment;
    exports homer.tastyworld.frontend.starterpack.utils.managers.external.printer;
    exports homer.tastyworld.frontend.starterpack.utils.managers.external.scale;
    exports homer.tastyworld.frontend.starterpack.utils.managers.external.sound;
    exports homer.tastyworld.frontend.starterpack.utils.managers.table;
    exports homer.tastyworld.frontend.starterpack.utils.managers.table.cursors;
    exports homer.tastyworld.frontend.starterpack.utils.misc;
    exports homer.tastyworld.frontend.starterpack.utils.ui;
    exports homer.tastyworld.frontend.starterpack.utils.ui.helpers;
    exports homer.tastyworld.frontend.starterpack.utils.ui.vkb;
}